[package]
name = "fraguracy"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = { git = "https://github.com/rust-bio/rust-htslib", rev = "6b1551829d98445fab6f89da06c0f86d38f379ce", features = ["libdeflate", "static", "gcs", "s3"] }
libc = "*"
clap = {version = "4.1.6", features = ["derive"]}
rustc-hash = "1.1.0"
lazy_static = "1.4.0"
ndarray = "0.15.6"
env_logger = "0.10.0"
log = "0.4.17"
itertools = "0.10.5"
#plotly = "0.8.3"
#polars = { version = "0.27.2", features = ["lazy", "strings"] }


[profile.release]
lto = "fat"
codegen-units = 1
