[package]
name = "fraguracy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = { version = "0.40.2", features = ["libdeflate", "static", "gcs", "s3"] }
libc = "*"
clap = "4.1.6"
rustc-hash = "1.1.0"

[profile.release]
lto = "fat"
codegen-units = 1
