[package]
name = "fraguracy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = { git = "https://github.com/rust-bio/rust-htslib", rev = "6b1551829d98445fab6f89da06c0f86d38f379ce", features = ["libdeflate", "static", "gcs", "s3"] }
libc = "*"
clap = "4.1.6"
rustc-hash = "1.1.0"
lazy_static = "1.4.0"

[profile.release]
lto = "fat"
codegen-units = 1
